#!/bin/bash

# Building run files for 48 Runs

cd 1 && nohup bash RUN.sh & 
cd 2 && nohup bash RUN.sh & 
cd 3 && nohup bash RUN.sh & 
cd 4 && nohup bash RUN.sh & 
cd 5 && nohup bash RUN.sh & 
cd 6 && nohup bash RUN.sh & 
cd 7 && nohup bash RUN.sh & 
cd 8 && nohup bash RUN.sh & 
cd 9 && nohup bash RUN.sh & 
cd 10 && nohup bash RUN.sh & 
cd 11 && nohup bash RUN.sh & 
cd 12 && nohup bash RUN.sh & 
cd 13 && nohup bash RUN.sh & 
cd 14 && nohup bash RUN.sh & 
cd 15 && nohup bash RUN.sh & 
cd 16 && nohup bash RUN.sh & 
cd 17 && nohup bash RUN.sh & 
cd 18 && nohup bash RUN.sh & 
cd 19 && nohup bash RUN.sh & 
cd 20 && nohup bash RUN.sh & 
cd 21 && nohup bash RUN.sh & 
cd 22 && nohup bash RUN.sh & 
cd 23 && nohup bash RUN.sh & 
cd 24 && nohup bash RUN.sh & 
cd 25 && nohup bash RUN.sh & 
cd 26 && nohup bash RUN.sh & 
cd 27 && nohup bash RUN.sh & 
cd 28 && nohup bash RUN.sh & 
cd 29 && nohup bash RUN.sh & 
cd 30 && nohup bash RUN.sh & 
cd 31 && nohup bash RUN.sh & 
cd 32 && nohup bash RUN.sh & 
cd 33 && nohup bash RUN.sh & 
cd 34 && nohup bash RUN.sh & 
cd 35 && nohup bash RUN.sh & 
cd 36 && nohup bash RUN.sh & 
cd 37 && nohup bash RUN.sh & 
cd 38 && nohup bash RUN.sh & 
cd 39 && nohup bash RUN.sh & 
cd 40 && nohup bash RUN.sh & 
cd 41 && nohup bash RUN.sh & 
cd 42 && nohup bash RUN.sh & 
cd 43 && nohup bash RUN.sh & 
cd 44 && nohup bash RUN.sh & 
cd 45 && nohup bash RUN.sh & 
cd 46 && nohup bash RUN.sh & 
cd 47 && nohup bash RUN.sh & 
cd 48 && nohup bash RUN.sh & 
