GLYHOME = /programs/repos/GLYLIB
GLYLIB = $(GLYHOME)/lib
GLYINC = $(GLYHOME)/inc
S1 = Get_Data_Comp_Score.c
E1 = get_data_comp_score

default:
	gcc -Wall $(S1) -I$(GLYINC) -L$(GLYLIB) -o $(E1) -lglylib -lm -g

