#GLYHOME = /programs/GLYLIB.git
GLYHOME = /programs/repos/GLYLIB
GLYLIB = $(GLYHOME)/lib
GLYINC = $(GLYHOME)/inc
S1 = Bin_PhiPsi_for_plots.c
E1 = bin_phipsi

default:
	gcc -Wall $(S1) -I$(GLYINC) -L$(GLYLIB) -o $(E1) -lglylib -lm -g


